### ISSUE TITLE
autor normalization: concatenated initials

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-schemas#221]
_From @annetteholtkamp on August 18, 2017 15:13_

## Expected Behavior
A name with concatenated capital initials like "Fitzakerley, DW" should be converted to
"Fitzakerley, D.W."
ex: https://inspirehep.net/record/1488707

This conversion should only happen, if the family name is not all caps since we may encounter Chinese names like "SHI, YU"

## Context
Currently, cataloguers have to change this manually which is painful for long author lists and may easily be overlooked. In the current system I believe this may generate  superfluous new author profiles. 

_Copied from original issue: inspirehep/inspire-next#2662_

**Comment by jacquerie** [comment]
_From @kaplun on August 22, 2017 9:5_

Is this happening in general (hence to be added to the workflow) or is only within certain sources (e.g. arXiv) (hence to be fixed in a crawler?)

**Comment by annetteholtkamp** [comment]
Difficult to say. It surely can happen for scanned conference proceedings. I can look around a bit.

- Annette

On 27 Aug 2017, at 01:09, Jacopo Notarstefano <notifications@github.com<mailto:notifications@github.com>> wrote:


From @kaplun<https://github.com/kaplun> on August 22, 2017 9:5

Is this happening in general (hence to be added to the workflow) or is only within certain sources (e.g. arXiv) (hence to be fixed in a crawler?)

**Comment by michamos** [comment]
This issue was moved to inspirehep/inspire-utils#30
