### ISSUE TITLE
documents -> url - remove url format?

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-schemas#274]
The field documents->url is defined as url but currently we also store paths (which makes validation on the editor fail)

<img width="845" alt="screen shot 2017-11-20 at 9 59 53 am" src="https://user-images.githubusercontent.com/580727/33010194-e34aecae-cdd9-11e7-8e4f-9ad359a456c2.png">

**Comment by michamos** [comment]
it turns out the `url` format is not defined by the JSON schema spec. Draft 4 defines `uri`, but is ambiguous as to whether it is an `URI` in the sense of [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) or a `URI-reference` (which could be relative instead of an absolute URI) instead. For this reason, [Draft 6](http://json-schema.org/draft-06/json-schema-migration-faq.html#formats-uri-vs-uri-reference) defines `uri` to be the former, whereas a `uri-reference` stands for the latter. 

So I am going to change all `url` `formats` to either `uri` or `uri-reference` depending on whether the content is an absolute URL or could be a relative one also. Any objections @jacquerie @david-caro ?
