### ISSUE TITLE
Reference simplification

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-schemas#39]
Originally we designed references to mimic mini-records. It looks like Catalogers will still want to curate them, so we shall simplify where possible the structure to make it nice when visualized in the record editor.

PR to soon come.

**Comment by michamos** [comment]
The reference schema has been finalized and the decision has been made to keep them similar to literature records. The main advantage of this is the ability to reuse the matcher with little modifications in order to match references to cited record. The UI problem to simplify reference curation is being handled in the record editor UI instead of the data model.
